apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-payload.fullname" . }}-server
  labels:
    {{- include "otel-payload.labels" . | nindent 4 }}
    role: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otel-payload.selectorLabels" . | nindent 4 }}
    role: server
